#!/usr/bin/env bash

# Exit on any error
set -e

# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a simple HTML file with "Hello World!"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Restart Nginx service to apply changes
sudo service nginx restart

# Optional: Check if Nginx is running
sudo service nginx status

