#!/usr/bin/env bash

# Install nginx web server and Redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Add the redirection and custom 404 page location blocks to the Nginx configuration
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=gfiqW1WaGbw;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
        return 404 "Ceci n'\''est pas une page\\n";
    }

    # Add custom header X-Served-By
    add_header X-Served-By \$hostname;

    # Additional server configuration...
}
EOL'

# Enable the new configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart nginx
sudo service nginx restart

