#!/usr/bin/env bash
#install HAProxy and deal with its configuration on the server

sudo apt-get update -y
sudo apt-get install haproxy -y

echo "
frontend haproxy
        bind *:80
        mode http
        default_backend servers
backend servers
        mode http
        balance roundrobin
        server 193545-web-01 18.206.206.7:80 check
        server 193545-web-02 100.24.253.51:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
